### ISSUE TITLE
`cargo test` double-panics on Linux

### ISSUE THREAD

**Issue by dwrensha** [carllerche/eventual_io#3]
```
thread '<unnamed>' panicked at '[unimplemented] failed to register interest with event loop', src/reactor.rs:326
```

I get the same error if I run the proxy example and try to open a connection to it.

I do not see this error on OSX.

**Comment by carllerche** [comment]
Yeah... this is related to error handling not being done yet :ghost:

**Comment by carllerche** [comment]
# This crate is deprecated!

This crate is deprecated in favor of [Tokio](https://github.com/tokio-rs/tokio).
